### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Ravvit528** [GoldieLeGenie/Dragon-quest-3HD2D-Randomizer#2]
Hello!
I enjoy new adventures with Landamizer every day

I have a request and will post it.
Is it possible to create random items including small medals?
Medal rewards are random, but medals do not come out.

Also, I would be happy if there is a version where the total number of randomized items is the same as the original.
I'd like to have a random adventure where items are stored only :)

Alternatively, if the appearance rate of items with high rare value decreases, there will be no problem.
Yesterday, 6 "Hero's Shield" appeared and I couldn't stop laughing. XD

こんにちは！
私は毎日ランダマイザーで新しい冒険を楽しんでいます

リクエストがあり、投稿します。
小さなメダルを含むランダムなアイテムを作成することは可能ですか？
メダル報酬はランダムですが、メダルはゲーム内に登場しません。

また、ランダム化したアイテムの総数がオリジナルと同じバージョンがあれば嬉しいです。
アイテムの場所だけがランダムな冒険をしたいです:)

もしくは、希少価値の高いアイテムの出現率が下がれば問題ありません。
昨日は"Hero's Shield"が6枚出現して笑いが止まりませんでしたXD

**Comment by GoldieLeGenie** [comment]
Hi, thank you very much for your feedback with the randomizer. I’ll take note of it and gradually incorporate your ideas. I appreciate you sharing your feedback to help improve the program and have a better experience with it !

**Comment by Ravvit528** [comment]
This is a fun and favorite MOD, so I'm looking forward to updating it in the future!

これはとても楽しくて大好きなMODなので、これからの更新も楽しみに待っています!

**Comment by GoldieLeGenie** [comment]
Haha, yes, it makes the game even more fun !

**Comment by GoldieLeGenie** [comment]
Okay, so regarding your idea that 'the total number of randomized items should be the same as the original,' what I did is ensure that area items are only randomized within their items that you get in areas, and shiny items are randomized only with other shiny items. is that ok ?

**Comment by Ravvit528** [comment]
Does that mean that in Ariahan, for example, the contents of the jar and barrel in Ariahan are only changed, and high-level equipment that does not originally exist in Ariahan is not available?
If that's the case, you may not be able to enjoy what's in it.
Can you replace the contents of treasure chests and jars from all over the world with the contents of treasure chests and jars from other places?
Shining object changes are very good in your way!

By the way, my current way of playing with Randomizer is,
I enjoy the Treasure Hunter role-play, which aims to fill the item list and advance the story.
Therefore, even if the total number is not exactly the same, there should be no problem if we can prevent the overflow of strong and rare items

Thank you for listening to my opinion!

ということは、例えばアリアハンでは、アリアハン内の壺や樽の中身が変わるだけで、もともとアリアハンにはない高級装備は使えないということですか？
そうなると、その中にあるものを楽しむことができなくなるかもしれません。
世界中の宝箱や瓶の中身を、ほかの場所の宝箱や瓶の中身に置き換えてもらえますか？
光り輝く物体の変更点はあなたのやり方でとても良いです！

ちなみに、私の現在のランダマイザの使い方は、
アイテムリストを埋めてストーリーを進めることを目的としたトレジャーハンターのロールプレイを楽しんでいます。
したがって、総数が全く同じではなくても、強くてレアなアイテムのオーバーフローを防ぐことができれば問題ないと思います

私の意見を聞いてくれてありがとうございます！

**Comment by GoldieLeGenie** [comment]
What I mean is, for example, Alihan chests, pots, etc., can contain only items available in other places like, for example, Rive, Romaria etc… so its what you want 👍 and for shinning object randomized only with shining so whit this is not posible to have 6 hero shield 😂

**Comment by Ravvit528** [comment]
That's very good!
If it's relatively easy to do... I would be happy if I could choose "complete random like before" and "random with the same total number as the original" according to the user's preference
Because six hero shields are funny and I like them🤣

それはとても良いです！
もしも比較的簡単にできるのであれば...”今までのような完全なランダム”と、"総数がオリジナルと同じランダム"をユーザーの好みで選択できたら嬉しいです
なぜならヒーローシールドが6枚というのもそれもまた笑えるし好きなのです🤣

**Comment by GoldieLeGenie** [comment]
yeah should be done in like 20-30 minutes !

**Comment by GoldieLeGenie** [comment]
okey v0.3 is available is you want to try it

**Comment by Ravvit528** [comment]
thank you!
I'll play right now!!

**Comment by Ravvit528** [comment]
![aaaaaa](https://github.com/user-attachments/assets/28a2b394-7f94-40b5-90af-62712a6f5444)
When I started "main.exe", I saw a display like this, what should I do?

**Comment by GoldieLeGenie** [comment]
Oops yeah my bad let me recompile it

**Comment by GoldieLeGenie** [comment]
okey should be good you can reinstall it

**Comment by Ravvit528** [comment]
I'm playing with a new version now

You can also find medals and see that they are shuffled.

Surprisingly, I found Hero's Shield in Ariahan.
Maybe I'm in a relationship with Hero's Shield🤣
![image](https://github.com/user-attachments/assets/a0b9c138-01b5-446d-8e49-319621d851a0)

**Comment by GoldieLeGenie** [comment]
Haha, you are lucky! This shield likes you 😆

**Comment by Ravvit528** [comment]
If you have time to spare, please adjust the order of medal rewards to randomize.
This is just my selfishness, so it's all right if you don't push yourself too hard

**Comment by GoldieLeGenie** [comment]
for mini-medals what's your idea same rewards randomized or only weapons and armor on it ?

**Comment by Ravvit528** [comment]
The problem I have right now is,
The problem is that if items that are originally only available in medal rewards are changed by randomization, they will not be available anywhere in the world.

Therefore, I would like you to change the order of the 24 rewards at random.

**Comment by GoldieLeGenie** [comment]
oh yeah you right about this

**Comment by juannerson** [comment]
this might be dumb but i cant open it ill try to open main and a black screen will flash then nothing

**Comment by GoldieLeGenie** [comment]
> this might be dumb but i cant open it ill try to open main and a black screen will flash then nothing

try to disable your windows defender and make sure everything is extracted

**Comment by juannerson** [comment]
> > this might be dumb but i cant open it ill try to open main and a black screen will flash then nothing
> 
> try to disable your windows defender and make sure everything is extracted

still nothing

**Comment by GoldieLeGenie** [comment]
hmmm i have no clue if you can record a quick video to see or just try to run it directly with python
