### ISSUE TITLE
non-randomized treasure chest

### ISSUE THREAD

**Issue by Ravvit528** [GoldieLeGenie/Dragon-quest-3HD2D-Randomizer#3]
Hi, how are you
I enjoyed playing random games today too,
I am writing to inform you that there were treasure chests that were not randomized here and there.

·Outdoor Treasure Box, east of "Aliahan Patty's Party Planning Place"
"Dragon Scale" is not randomized.

·"Skyfell Tower" All treasure chests have the same contents as the original.

·"Underground Lake" All treasure chests have the same contents as the original.

However, if the contents are Gold, the amount included is random.

**Comment by GoldieLeGenie** [comment]
can you send me your .pak please

**Comment by Ravvit528** [comment]
[https://104.gigafile.nu/1209-b127d9e40f07312c75c3b6e4704c5bc7c](url)
![image](https://github.com/user-attachments/assets/ba01c078-8b80-40e2-b28b-6d6ac4f8c599)
You can download it from this button

**Comment by GoldieLeGenie** [comment]
hmm in your pak nothing is randomized here for items

**Comment by GoldieLeGenie** [comment]
okey i just found the problem thanks for reporting it :) you can reinstall should be fixed

**Comment by Ravvit528** [comment]
thank you!
